#!/bin/bash

## #ddev-generated
## Description: Run PHPQA test
## Usage: dphpqa
## Example: "ddev dphpqa"
## ProjectTypes: drupal7,drupal8,drupal9,backdrop

docker run -it -u "$(id -u)" --rm --workdir="/app" -v "$(pwd)":/app lucacracco/phpqa:latest bash -c "/tools/edgedesign-phpqa/vendor/bin/phpqa --config=.phpqa"
