phpqa:
  analyzedDirs: web/modules/custom
  buildDir: reports
  ignoredDirs: node_modules
  ignoredFiles: ""
  report: true
  #verbose: true
  # execution: no-parallel
  tools:
    - phploc
    - phpcpd
    - phpcs
    - pdepend
    - phpmd
    - phpmetrics
    - security-checker
    - phpstan
    - psalm
  extensions:
    - php
    - inc
    - module
    - install
    - test
    - profile
    - theme
    - yml
    - css
    - js

phpcs:
  # alternatively you can use an array to define multiple standards (https://github.com/squizlabs/PHP_CodeSniffer/wiki/Usage#specifying-a-coding-standard)
  standard: .phpcs.xml
  # number of allowed errors is compared with warnings+errors, or just errors from checkstyle.xml
  ignoreWarnings: false
  # https://github.com/squizlabs/PHP_CodeSniffer/wiki/Reporting
  reports:
    cli:
      - full
    file:
      checkstyle: checkstyle.xml

phpmd:
  # alternatively you can use an array to define multiple rule sets (https://phpmd.org/documentation/index.html#using-multiple-rule-sets)
  standard: phpmd.xml

pdepend:
# coverageReport: build/coverage-clover.xml

phpcpd:
  minLines: 5
  minTokens: 70

phpmetrics:
  # v1
  config: null
  # v2
  git: false
  # junit: build/log-junit.xml
  # composer: composer.json

phpstan:
  level: 3
  # https://github.com/phpstan/phpstan#configuration
  standard: phpstan.neon

psalm:
  config: .psalm.xml
  deadCode: false
  threads: 1
  showInfo: true
  allowMissingFiles: true