#!/bin/bash

## Description: Run Behat
## Usage: behat [flags] [args]
## Example: "ddev phpunit --tags tag1"
## ProjectTypes: drupal7,drupal8,drupal9,backdrop

php ./vendor/bin/behat --config=./behat/behat.yml $@
