#!/bin/bash

## Description: Run Nightwatch
## Usage: nightwatch [flags] [args]
## Example: "ddev nightwatch" or "ddev nightwatch --tag core"
## ProjectTypes: drupal8,drupal9

yarn --cwd /var/www/html/web/core test:nightwatch $@
