#!/bin/bash

## Description: Run PHPQA
## Usage: phpqa [flags] [args]
## Example: "ddev phpqa" or "ddev phpqa --tools phpcs"
## ProjectTypes: drupal8,drupal9

mkdir -p ./reports
chmod -R 775 ./reports

php ./vendor/bin/phpqa --config=.phpqa $@
