#!/bin/bash

## Description: Run PHPQA
## Usage: phpqa [flags] [args]
## Example: "ddev phpqa" or "ddev phpqa --tools phpcs"
## ProjectTypes: drupal7,drupal8,drupal9,backdrop

mkdir -p reports
chmod -R 777 reports

php ./vendor/bin/phpqa --config=.phpqa $@
