#!/bin/bash

## Description: Run PHPUnit
## Usage: phpunit [flags] [args]
## Example: "ddev phpunit --group big_pipe" or "ddev phpunit core/modules/action"
## ProjectTypes: drupal8,drupal9,drupal10

mkdir -p sites/simpletest/browser_output
chmod -R 777 sites/simpletest/browser_output

php ./vendor/bin/robo phpunit $@
