name: Upload Release

on:
  push:
    tags:
    - 'v*'

jobs:
  build:
    name: Upload Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build project
        run: |
          zip -r d8-composer drupal8-composer
          zip -r d8-recommended drupal8-recommended
          zip -r symfony symfony
          zip -r symfony-website symfony-website
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
      - name: Upload Release drupal8-composer
        id: upload_release_d8_composer
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./d8-composer.zip
          asset_name: d8-composer.zip
          asset_content_type: application/zip
      - name: Upload Release drupal8-recommended
        id: upload_release_d8_recommended
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./d8-recommended.zip
          asset_name: d8-recommended.zip
          asset_content_type: application/zip
      - name: Upload Release symfony
        id: upload_release_symfony
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./symfony.zip
          asset_name: symfony.zip
          asset_content_type: application/zip
      - name: Upload Release symfony-website
        id: upload_release_symfony_website
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./symfony-website.zip
          asset_name: symfony-website.zip
          asset_content_type: application/zip